### ISSUE TITLE
Profile aesthetic image overlaps meta data in mobile view

### ISSUE THREAD

**Issue by littlelark** [littlelark/jcink-the-breach#15]
![Screenshot_20191230-081222](https://user-images.githubusercontent.com/21272110/71572648-5efb9700-2a9d-11ea-8644-d3f979b7ba59.png)

**Comment by littlelark** [comment]
To do:
- [ ] Clean up layout
- [ ] Make secondary image square

Ideas for comments tab emptiness concerns:
- Background image?
- Center them
- Repeat secondary image with them
- Move down next to stat bars?

**Comment by littlelark** [comment]
- [ ] Add more spacing between stat bar and label
- [ ] Make no-gos label a touch smaller
- [ ] Make no-gos stay within height of avatar
- [ ] Make meta tab handle narrow width displays better
- [ ] Stat bars not responding to input
- [ ] Style comments

![unknown](https://user-images.githubusercontent.com/21272110/72179571-6cb8f280-33a2-11ea-9508-653228628a32.png)
![unknown2](https://user-images.githubusercontent.com/21272110/72179572-6cb8f280-33a2-11ea-9b28-0455d0ac2ab0.png)
![unknown3](https://user-images.githubusercontent.com/21272110/72179573-6cb8f280-33a2-11ea-9c09-5758cfd5a890.png)

**Comment by littlelark** [comment]
Original for reference: http://scratchpad.io/overconfident-committee-8651#fullscreen
